version: '3.4'

services:
  web:
    container_name: nl-scrape-web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    restart: always
    volumes:
      - .:/nl-scrape-web
    ports:
      - "8000:8000"